### ISSUE TITLE
Note Classifier: C doesn't recognize small negative offsets

### ISSUE THREAD

**Issue by dbgrande** [flarn2006/SparketteVCV#2]
When I hook up Note Classifier to Bogaudio Reftone, I can see that all the notes recognize ±50 cent offsets except for the C note, which only recognizes positive offsets. That leaves a gap of 50 cents that isn't recognized as any note.

**Comment by flarn2006** [comment]
Confirmed; thanks for the report.

**Comment by flarn2006** [comment]
Just fixed it and submitted the update. Thanks again! :)
